name: Node.js CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          always-auth: true
          node-version: "${{ matrix.node-version }}"
      - run: yarn
      - run: yarn build
      - run: yarn test
      - run: yarn workspace @rowsncolumns/storybook run deploy-storybook -- --ci
        env:
          CI: true
